dataset:
  name: "DeepAccident"
  path: "/media/nadya/86bf701c-9a26-47cf-89c1-3a952cb40cc1/DeepAccident"
  prefixes:
    - "train"
    - "valid"

ego_vehicle:
  name: "ego_vehicle"
  type: "basic"  # [basic, aggregating, broadcasting, hybrid]
  parameters:
    fps: 20 #frames per second
    prediction_horizon: 2 # seconds
    prediction_frequency: 5 
    forecasting_frequency: 10

  detector:
    name: "gt"    # [gt, centerpoint]
    mode: "eval"           # train => save checkpoint, eval => load checkpoint
    checkpoint: "/path/to/centerpoint_eval.ckpt"

  tracker:
    class: "AB3DMOT"
    # No mode or checkpoint needed, as it's algorithmic

  predictor:
    name: "lstm"   # [lstm, gcn, gat, gcn_temporal, gat_temporal, transformer, transformer_gnn]
    mode: "eval"  
    checkpoint: "/path/to/lstm_eval.ckpt"
    # No 'parameters' block here; we moved those fields to vehicle-level parameters

  broadcaster:
    broadcasting_frequency: 10
    broadcasting_range: 50

  sensors:
    - "lidar01"


vehicles:
  vehicle_1:
    name: "ego_vehicle_behind"
    type: "basic"
    parameters:
      fps: 20
      prediction_horizon: 2
      prediction_frequency: 5
      forecasting_frequency: 10

    detector:
      name: "gt"   # could be ground-truth
      # no mode/checkpoint needed if just 'gt'

    tracker:
      class: "AB3DMOT"

    predictor:
      name: "gat_temporal"
      mode: "train"
      checkpoint: "/path/to/gat_temporal_train.ckpt"

    broadcaster:
      broadcasting_frequency: 10
      broadcasting_range: 50

    sensors:
      - "lidar01"

  vehicle_2:
    name: "other_vehicle"
    type: "basic"
    parameters:
      fps: 10
      prediction_horizon: 2
      prediction_frequency: 5
      forecasting_frequency: 10

    detector:
      name: "gt"
      mode: "eval"
      checkpoint: "/path/to/pointpillars_eval.ckpt"

    tracker:
      class: "AB3DMOT"

    predictor:
      name: "transformer"
      mode: "eval"
      checkpoint: "/path/to/transformer_eval.ckpt"

    broadcaster:
      broadcasting_frequency: 10
      broadcasting_range: 50

    sensors:
      - "lidar01"

  vehicle_3:
    name: "other_vehicle_behind"
    type: "basic"
    parameters:
      fps: 10
      prediction_horizon: 2
      prediction_frequency: 5
      forecasting_frequency: 10

    detector:
      name: "gt"
      mode: "train"
      checkpoint: "/path/to/centerpoint_train.ckpt"

    tracker:
      class: "AB3DMOT"

    predictor:
      name: "transformer_gnn"
      mode: "train"
      checkpoint: "/path/to/transformer_gnn_train.ckpt"

    broadcaster:
      broadcasting_frequency: 10
      broadcasting_range: 50

    sensors:
      - "lidar01"
