dataset:
  name: "DeepAccident"
  path: "/media/nadya/86bf701c-9a26-47cf-89c1-3a952cb40cc1/DeepAccident"
  global_coordinates: false
  split: "valid" # ["train", "valid", "test"]
  preprocessed: false

ego_vehicle: "vehicle_4"

vehicles:
  vehicle_1:
    type: "broadcasting"
    parameters:
      tracking_history: 20 # bbox to save 
      keep_track: 10
      prediction_frequency: 10
      prediction_horizon: 2
      device: "cuda:0"

    detector:
      name: "gt_occ"    # [gt, gt_occ, centerpoint]
      #detections: "data/detections/DeepAccident/noisy_observations_kf/val/other_vehicle"

    tracker:
      name: "gt"

    predictor:
      name: "lstm_nll"
      checkpoint: "train_predictor/checkpoints/DeepAccident_lstm_nll_10_20_10.pth"

    broadcaster:
      broadcasting_frequency: 10
      topic: "pred"
    
    listener:
      topic: "pred"

    sensors:
      - "lidar01"

  vehicle_2:
    type: "broadcasting"  # [basic, aggregating, broadcasting, hybrid]
    parameters:
      tracking_history: 20 # bbox to save 
      keep_track: 10
      prediction_frequency: 10 
      prediction_horizon: 2
      device: "cuda:0" #options [cuda, cpu, cuda:1]
    
    detector:
      name: "gt_occ"    # [gt, centerpoint] 
      #detections: "data/detections/DeepAccident/noisy_observations/val/ego_vehicle"
    
    tracker:
      name: "gt" #[gt, gt_noise, ab3dmot]
      # No mode or checkpoint needed, as it's algorithmic
    
    predictor:
      name: "lstm_nll"   # [lstm, lstm_cat, transformer, transformer_cat]
      checkpoint: "train_predictor/checkpoints/DeepAccident_lstm_nll_10_20_10.pth"
    
    broadcaster:
      broadcasting_frequency: 10
      topic: "pred"
      
    listener:
      topic: "pred"
    
    sensors:
      - "lidar01"
      
      
  vehicle_3:
    type: "broadcasting"
    parameters:
      tracking_history: 20 # bbox to save 
      keep_track: 10
      prediction_frequency: 10
      prediction_horizon: 2
      device: "cuda:0"
    
    detector:
      name: "gt_occ"   
     
    tracker:
      name: "gt"
    
    predictor:
      name: "lstm_nll"
      checkpoint: "train_predictor/checkpoints/DeepAccident_lstm_nll_10_20_10.pth" 
      # "fps", "prediction_horizon", "prediction_sampling" are fetched form the predictor
    
    broadcaster:
      broadcasting_frequency: 10
      topic: "pred"
      
    listener:
      topic: "pred"
    
    sensors:
      - "lidar01"
      
  vehicle_4:
    type: "aggregating"
    parameters:
      tracking_history: 20 # bbox to save 
      keep_track: 10
      prediction_frequency: 10
      prediction_horizon: 2
      device: "cuda:0"
    
    detector:
      name: "gt_occ"   
     
    tracker:
      name: "gt"
    
    predictor:
      name: "lstm_nll"
      checkpoint: "train_predictor/checkpoints/DeepAccident_lstm_nll_10_20_10.pth" 
      # "fps", "prediction_horizon", "prediction_sampling" are fetched form the predictor
    
    broadcaster:
      broadcasting_frequency: 10
      topic: "pred"
      
    listener:
      topic: "pred"
    
    sensors:
      - "lidar01"