dataset:
  name: "DeepAccident"
  path: "/media/nadya/86bf701c-9a26-47cf-89c1-3a952cb40cc1/DeepAccident"
  prefixes:
    - "train"
    - "valid"
  fps: 10  
  preprocessed: true

ego_vehicle:
  name: "other_vehicle"
  type: "basic"
  parameters:
    fps: 10
    tracking_history: 20 # bbox to save 
    keep_track: 3
    prediction_horizon: 2
    prediction_frequency: 10
    prediction_sampling: 10
    device: "cuda:0"

  detector:
    name: "gt_occ"    # [gt, gt_occ, centerpoint]
    #det_path: "data/detections/DeepAccident/noisy_observations_kf/val/other_vehicle"

  tracker:
    name: "gt"

  predictor:
    name: "lstm_nll"
    mode: "train"
    checkpoint: "checkpoints/prediction/10_20_vx_vy/other_vehicle/lstm_predictor_nll.pth"
    #mode: "train" #["train"] 
    data_path: "data/prediction/DeepAccident/10_20/other_vehicle"
    save_path: "checkpoints/prediction/10_20_vx_vy/other_vehicle"

  broadcaster:
    broadcasting_frequency: 10
    broadcasting_range: 50

  sensors:
    - "lidar01"

vehicles:
  vehicle_1:
    name: "ego_vehicle"
    type: "basic"  # [basic, aggregating, broadcasting, hybrid]
    parameters:
      fps: 10 #frames per second
      tracking_history: 10 # bbox to save 
      keep_track: 3
      prediction_horizon: 2 # seconds
      prediction_frequency: 10 
      prediction_sampling: 10
      device: "cuda:0" # options [cuda, cpu, cuda:1]
    
    detector:
      name: "gt"    # [gt, centerpoint] 
      #det_path: "data/detections/DeepAccident/noisy_observations/val/ego_vehicle"
    
    tracker:
      name: "gt" #[gt, gt_noise, ab3dmot]
      # No mode or checkpoint needed, as it's algorithmic
    
    predictor:
      name: "lstm"   # [lstm, lstm_cat, transformer, transformer_cat]
      mode: "eval"
      checkpoint: "checkpoints/prediction/10_20_vx_vy/ego_vehicle/lstm_predictor.pth"
      #mode: "train" #["train"] 
      #data_path: "data/prediction/DeepAccident/10_20/ego_vehicle"
      #save_path: "checkpoints/prediction/10_20_vx_vy_vyaw/ego_vehicle/"
    
    broadcaster:
      broadcasting_frequency: 10
      broadcasting_range: 50
    
    sensors:
      - "lidar01"


  vehicle_2:
    name: "ego_vehicle_behind"
    type: "basic"
    parameters:
      fps: 10
      tracking_history: 10 # bbox to save 
      keep_track: 3
      prediction_horizon: 2
      prediction_frequency: 10
      prediction_sampling: 10
      device: "cuda:0"
    
    detector:
      name: "gt"   
     
    tracker:
      name: "gt"
    
    predictor:
      name: "lstm"
      mode: "eval"
      checkpoint: "checkpoints/prediction/10_20_vx_vy/ego_vehicle_behind/lstm_predictor.pth"
    
    broadcaster:
      broadcasting_frequency: 10
      broadcasting_range: 50
    
    sensors:
      - "lidar01"
    

  vehicle_3:
    name: "other_vehicle_behind"
    type: "basic"
    parameters:
      fps: 10
      tracking_history: 10 # bbox to save 
      keep_track: 3
      prediction_horizon: 2
      prediction_frequency: 10
      prediction_sampling: 10
      device: "cuda:0"

    detector:
      name: "gt"

    tracker:
      name: "gt"

    predictor:
      name: "lstm"
      mode: "eval"
      checkpoint: "checkpoints/prediction/10_20_vx_vy/other_vehicle_behind/lstm_predictor.pth"

    broadcaster:
      broadcasting_frequency: 10
      broadcasting_range: 50

    sensors:
      - "lidar01"
