dataset:
  name: "V2V4Real"
  path: "preprocess/preprocessed/V2V4Real"
  split: "test" # ["train", "valid", "test"]
  fps: 10

ego_vehicle: "vehicle_2"

vehicles:
  vehicle_1:
    type: "broadcasting"
    parameters:
      tracking_buffer_s: 2.0
      observed_past_s: 1.0
      prediction_horizon_s: 2.0
      device: "cuda:1"

    detector:
      #name: "gt_occ"
      name: "centerpoint"    # [gt, gt_occ, centerpoint]
      detections: "detections/test/v2v_test_50/0"

    tracker:
      # name: "id_association"
      name: "metric_association"

    predictor:
      name: "lstm_nll"     
      checkpoint: "train_predictor/checkpoints/V2V4Real_lstm_nll_10_20_10.pth"

    broadcaster:
      broadcasting_interval_s: 0.1
      topic: "pred"
    
    listener:
      topic: "pred"


    sensors:
      - "lidar01"

  vehicle_2:
    type: "basic"
    parameters:
      tracking_buffer_s: 2.0
      observed_past_s: 1.0
      prediction_horizon_s: 2.0
      device: "cuda:1"

    detector:
      name: "gt"
      #name: "centerpoint"    # [gt, gt_occ, centerpoint]
      #detections: "detections/test/v2v_test_50/1"

    tracker:
      name: "id_association"
      # name: "metric_association"

    predictor:
      name: "lstm_nll"     
      checkpoint: "train_predictor/checkpoints/V2V4Real_lstm_nll_10_20_10.pth"

    broadcaster:
      broadcasting_interval_s: 0.1
      topic: "pred"
    
    listener:
      topic: "pred" #drop: true

    sensors:
      - "lidar01"
